baseURL = 'https://dublin-digital-radio.github.io/ac-2025-website-prototype/'
languageCode = 'en-us'
title = 'Alternating Current 2025'
theme = 'gokarna'

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Programme"
url = "/programme/"
weight = 2
